version: '3'

networks:
  docker_host:
    driver: bridge  # Use an overlay network for better isolation

services:
  papertrl-proxy:
    build:
      context: proxy-service  # Replace with the actual path to the proxy-service Dockerfile
    container_name: papertrl-proxy
    ports:
      - "8082:8082"
    networks:
      - docker_host

  papertrl-auth:
    build:
      context: auth-service  # Replace with the actual path to the auth-service Dockerfile
    container_name: papertrl-auth
    ports:
      - "9000:9000"  # Use a different port to avoid conflicts with proxy-service
    networks:
      - docker_host

  papertrl-common:
    build:
      context: common-service  # Replace with the actual path to the auth-service Dockerfile
    container_name: papertrl-common
    ports:
      - "9008:9008"  # Use a different port to avoid conflicts with proxy-service
    networks:
      - docker_host

  papertrl-umm:
    build:
      context: user-management-service  # Replace with the actual path to the auth-service Dockerfile
    container_name: papertrl-umm
    ports:
      - "9003:9003"  # Use a different port to avoid conflicts with proxy-service
    networks:
      - docker_host

  papertrl-integration:
    build:
      context: integration-service  # Replace with the actual path to the auth-service Dockerfile
    container_name: papertrl-integration
    ports:
      - "9006:9006"  # Use a different port to avoid conflicts with proxy-service
    networks:
      - docker_host

  papertrl-vp:
    build:
      context: vp-service  # Replace with the actual path to the auth-service Dockerfile
    container_name: papertrl-vp
    ports:
      - "9002:9002"  # Use a different port to avoid conflicts with proxy-service
    networks:
      - docker_host

  papertrl-tenant:
    build:
      context: tenant-service  # Replace with the actual path to the auth-service Dockerfile
    container_name: papertrl-tenant
    ports:
      - "9004:9004"  # Use a different port to avoid conflicts with proxy-service
    networks:
      - docker_host

  papertrl-payment:
    build:
      context: payment-service  # Replace with the actual path to the auth-service Dockerfile
    container_name: papertrl-payment
    ports:
      - "5060:5060"  # Use a different port to avoid conflicts with proxy-service
    networks:
      - docker_host

  papertrl-message:
    build:
      context: message-service  # Replace with the actual path to the auth-service Dockerfile
    container_name: papertrl-message
    ports:
      - "5020:5020"  # Use a different port to avoid conflicts with proxy-service
    networks:
      - docker_host

  front-end:
    build:
      context: front_end  # Replace with the actual path to the auth-service Dockerfile
    container_name: front-end
    ports:
      - "4200:4200"  # Use a different port to avoid conflicts with proxy-service
    networks:
      - docker_host
